#!/bin/sh
#Notification
dunst &

#Hide cursor when inactive
unclutter --timeout 5 --jitter 2 --ignore-scrolling -b

#Daemons
#pgrep deviceNo || ~/.scripts/deviceNotify.sh &
#pgrep mpcNo || ~/.scripts/mpcNotify.sh &
pgrep urxvtd || urxvtd -q -o -f
pgrep transmission-da || transmission-daemon -g .config/transmission

#Keyboard Tuning
xset r rate 250 40

display_Extend.sh

##Composition
#compton -b &
#
#sleep 0.2
#
##Background
#~/.fehbg
#^Handled in display_Extend.sh^
